### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: nx run workspace:version --version=minor

### ISSUE THREAD

**Issue by mtrefzer** [jscutlery/semver#230]
After `nx migrate latest` (12.5.5) and `nx g @nrwl/workspace:convert-to-nx-project --all` I'm running into the following error using `@jscutlery/semver@2.3.1`:

`nx run workspace:version --version=minor`

results in

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.resolve (path.js:1039:7)
    at node_modules/@jscutlery/semver/src/builders/version/utils/workspace.js:36:165
    at Array.map (<anonymous>)
    at MapSubscriber.project (node_modules/@jscutlery/semver/src/builders/version/utils/workspace.js:36:141)
    at MapSubscriber._next (node_modules/@jscutlery/semver/node_modules/rxjs/internal/operators/map.js:49:35)
    at MapSubscriber.Subscriber.next (node_modules/@jscutlery/semver/node_modules/rxjs/internal/Subscriber.js:66:18)
    at CatchSubscriber.SimpleOuterSubscriber.notifyNext (node_modules/@jscutlery/semver/node_modules/rxjs/internal/innerSubscribe.js:69:26)
    at SimpleInnerSubscriber._next (node_modules/@jscutlery/semver/node_modules/rxjs/internal/innerSubscribe.js:27:21)
    at SimpleInnerSubscriber.Subscriber.next (node_modules/@jscutlery/semver/node_modules/rxjs/internal/Subscriber.js:66:18)

```

**Comment by edbzn** [comment]
Hello, this was fixed in `@jscutlery/semver@2.4.0`, thanks for reporting!
