### ISSUE TITLE
nx:run-commands as postTarget receives extraneous arguments

### ISSUE THREAD

**Issue by Phault** [jscutlery/semver#554]
After updating from Nx 14.1.5 to 14.3.6, my postTargets that use nx:run-commands with `npm publish` started failing with an odd error:
```bash
[eslint-config] ❌ Error: ERROR: Something went wrong in run-commands - Command failed: npm publish --command="npm publish" --cwd=libs/eslint-config --__unparsed__= --parallel=true --color=false
    at /Users/me/someNxProject/node_modules/nx/src/executors/run-commands/run-commands.impl.js:59:19
    at Generator.throw (<anonymous>)
    at rejected (/Users/me/someNxProject/node_modules/tslib/tslib.js:116:69)
```
Note all the extra arguments after `npm publish`. Weirdly enough if I just run the postTarget task directly then it works just fine, which leads me to believe it was caused by this Nx change: https://github.com/nrwl/nx/commit/da1faaf483668227b9a7e8706426c93846c5ef4a 

I _think_ this might be a bug in Nx, but I saw that you're doing some special enhancing of the options before passing them to runExecutor, so I'm really not certain.

As a workaround, I've simply disabled `forwardAllArgs` for the time being.

**Comment by Phault** [comment]
Turns out this is because nx:run-commands just appends whatever its `options.__unparsed__` contains, regardless of whether it contains a parameter that it owns itself such as "color", "command", etc. The reason it just now became a problem, is because `__unparsed__` wasn't set when using runExecutor() prior to https://github.com/nrwl/nx/commit/da1faaf483668227b9a7e8706426c93846c5ef4a 

This is a bug in the run-commands executor, so I'm closing the issue.
