### ISSUE TITLE
Version executor is failing to get version when merged to main

### ISSUE THREAD

**Issue by minuz** [jscutlery/semver#633]
Hi, I've been trying to implement the semver into my monorepo using nx and when running within a PR, it works fine and it calculates everything. Once the PR is merged, it's failing to calculate the new version. 

The command sample is as follows: 
```
nx affected --base=$(git rev-parse origin/main~1) --head=$(git rev-parse HEAD) --target=version -c=production
```

``` bash
    ✖  nx run shared-util-feature-flag:version:production
       [shared-util-feature-flag] 🆕 Calculated new version "null".
       [shared-util-feature-flag] ❌ TypeError: Cannot read properties of null (reading 'toString')
           at /Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/src/executors/version/utils/template-string.js:9:81
           at Array.reduce (<anonymous>)
           at createTemplateString (/Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/src/executors/version/utils/template-string.js:7:33)
           at formatCommitMessage (/Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/src/executors/version/utils/commit.js:26:55)
           at /Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/src/executors/version/index.js:76:68
           at /Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:35
           at OperatorSubscriber._this._next (/Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
           at OperatorSubscriber.Subscriber.next (/Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
           at /Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/node_modules/rxjs/dist/cjs/internal/operators/switchMap.js:17:192
           at OperatorSubscriber._this._next (/Users/fernando.baba/Dev/repos/expedo-fe/node_modules/@jscutlery/semver/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
```

My target config is: 
``` json
    "version": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "tagPrefix": "@expedo/feature-flag-",
        "trackDeps": true,
        "noVerify": true
      },
      "configurations": {
        "development": {
          "releaseAs": "prerelease",
          "preid": "beta",
          "skipProjectChangelog": true,
          "skipCommit": true
        },
        "production": {
          "releaseAs": "release"
        }
      }
    },
```

Any help will be appreciated! Thanks :)

**Comment by edbzn** [comment]
Hi, it is the same problem as I described [here](https://github.com/jscutlery/semver/issues/631#issuecomment-1379420057).
