### ISSUE TITLE
Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

### ISSUE THREAD

**Issue by mklueh** [jscutlery/semver#757]
Nx  is suddenly failing in my project when triggering the semver task

```
yarn nx affected --push=true --parallel=1 --target=version --baseBranch=master --preid=alpha --releaseAs=prerelease --skip-root-changelog --skip-project-changelog --dryRun=true

 >  NX   No explicit --base argument provided, but found environment variable NX_BASE so using its value as the affected base: da1336a182eb4f861546e9cb6cfc2d03aea325c4


 >  NX   No explicit --head argument provided, but found environment variable NX_HEAD so using its value as the affected head: 9ce655de2b0be254bcd5a5c4fbf5f2ea9a66bb08

ERROR (1) when writing 
ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~10b92709'
Error: ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~10b92709'
    at writeFileSync (node:fs:2352:20)
    at writeJsonFile (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/utils/fileutils.js:55:28)
    at writeCache (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/nx-deps-cache.js:101:43)
    at buildProjectGraphUsingProjectFileMap (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/build-project-graph.js:65:40)
    at async buildProjectGraphWithoutDaemon (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:72:27)
    at async createProjectGraphAsync (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:121:25)
    at async Object.affected (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/command-line/affected/affected.js:33:26)
ERROR (2) when writing 
ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~3f4e0193'
Error: ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~3f4e0193'
    at writeFileSync (node:fs:2352:20)
    at writeJsonFile (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/utils/fileutils.js:55:28)
    at writeCache (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/nx-deps-cache.js:101:43)
    at buildProjectGraphUsingProjectFileMap (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/build-project-graph.js:65:40)
    at async buildProjectGraphWithoutDaemon (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:72:27)
    at async createProjectGraphAsync (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:121:25)
    at async Object.affected (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/command-line/affected/affected.js:33:26)
ERROR (3) when writing 
ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~4f8666c0'
Error: ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~4f8666c0'
    at writeFileSync (node:fs:2352:20)
    at writeJsonFile (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/utils/fileutils.js:55:28)
    at writeCache (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/nx-deps-cache.js:101:43)
    at buildProjectGraphUsingProjectFileMap (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/build-project-graph.js:65:40)
    at async buildProjectGraphWithoutDaemon (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:72:27)
    at async createProjectGraphAsync (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:121:25)
    at async Object.affected (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/command-line/affected/affected.js:33:26)
ERROR (4) when writing 
ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~53db5a46'
Error: ENOENT: no such file or directory, open '/home/runner/work/my-workspace/my-workspace/.nx/cache/project-graph.json~53db5a46'
    at writeFileSync (node:fs:2352:20)
    at writeJsonFile (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/utils/fileutils.js:55:28)
    at writeCache (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/nx-deps-cache.js:101:43)
    at buildProjectGraphUsingProjectFileMap (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/build-project-graph.js:65:40)
    at async buildProjectGraphWithoutDaemon (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:72:27)
    at async createProjectGraphAsync (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:121:25)
    at async Object.affected (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/command-line/affected/affected.js:33:26)

 >  NX   Running target version for project my-app:

    - my-app
   
   With additional flags:
     --push=true
     --baseBranch=master
     --preid=alpha
     --releaseAs=prerelease
     --skip-root-changelog=true
     --skip-project-changelog=true
     --dryRun=true

 

> nx run my-app:version --push=true --baseBranch=master --preid=alpha --releaseAs=prerelease --skip-root-changelog --skip-project-changelog --dryRun=true

Could not find 'nx' module in this workspace. Error: [readCachedProjectGraph] ERROR: No cached ProjectGraph is available.

If you are leveraging \`readCachedProjectGraph()\` directly then you will need to refactor your usage to first ensure that
the ProjectGraph is created by calling \`await createProjectGraphAsync()\` somewhere before attempting to read the data.

If you encounter this error as part of running standard \`nx\` commands then please open an issue on https://github.com/nrwl/nx
    at readCachedProjectGraph (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/project-graph/project-graph.js:30:15)
    at run (/home/runner/work/my-workspace/my-workspace/node_modules/nx/src/command-line/run/run.js:151:69)
    at process.<anonymous> (/home/runner/work/my-workspace/my-workspace/node_modules/nx/bin/run-executor.js:59:48)
    at process.emit (node:events:519:28)
    at emit (node:internal/child_process:951:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:83:21)

 

 >  NX   Running target version for project my-app failed

   Failed tasks:
   
   - my-app:version

Error: Process completed with exit code 1.
```

My regular pipeline using nx affected still works fine if I disable the versioning step.

**I'd appreciate any hints as I have no idea what is going on.**

**Comment by mklueh** [comment]
Error seems to be gone after some dependency upgrades

**Comment by edbzn** [comment]
Closing, feel free to reopen.
