### ISSUE TITLE
@jscutlery/semvver:github executor failing

### ISSUE THREAD

**Issue by jdwillmsen** [jscutlery/semver#789]
When using the @jscutlery/semvver:github executor I am encountering a failure.

![image](https://github.com/jscutlery/semver/assets/42048994/7f0d1791-ab8e-45ba-be98-551f0103b7d0)
![image](https://github.com/jscutlery/semver/assets/42048994/c45527b0-57f8-4f2f-bede-66010a472b69)

This error happens in ci as well as locally.

It happens even when it's a post-target of the version executor.

**Comment by ontoneio** [comment]
Having the same issue, but it's claiming to be an issue with `gh auth login`

```bash
Error: HTTP 401: Bad credentials (URL/releases)
Try authenticating with:  gh auth login

    at /workspaces/node_modules/@jscutlery/semver/src/executors/common/exec.js:10:34
    at ChildProcess.exithandler (node:child_process:430:5)
    at ChildProcess.emit (node:events:517:28)
    at maybeClose (node:internal/child_process:1098:16)
    at ChildProcess._handle.onexit (node:internal/child_process:303:5)
[mgnl-base] ❌ Error: Something went wrong with post-target "mgnl-base:github".
    at /workspaces/node_modules/@jscutlery/semver/src/executors/version/utils/post-target.js:27:27
    at Generator.next (<anonymous>)
    at fulfilled (/workspaces/node_modules/tslib/tslib.js:164:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
