### ISSUE TITLE
`@jscutlery:version` executor failing with @nx v19.0.4

### ISSUE THREAD

**Issue by marcolongol** [jscutlery/semver#820]
The latest oficial `@jscutlery/semver` release (v5.2.2) still has `@nx/devkit` ^18.0.0 listed as peer dependency, upgrading `@nx` to v19.0.4 causes `@jscutlery:version` executor to fail with error below, since the `Workspaces` symbol was removed in `@nx` v19.0.0

```
   [common-ui] ❌ TypeError: Workspaces is not a constructor
      at readTargetOptions (/home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/@nx/devkit/src/executors/read-target-options.js:26:16)
      at /home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/@jscutlery/semver/src/executors/version/utils/post-target.js:18:53
      at Generator.next (<anonymous>)
      at /home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/tslib/tslib.js:169:75
      at new Promise (<anonymous>)
      at Object.__awaiter (/home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/tslib/tslib.js:165:16)
      at /home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/@jscutlery/semver/src/executors/version/utils/post-target.js:10:104
      at Observable._subscribe (/home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/rxjs/dist/cjs/internal/observable/defer.js:8:31)
      at Observable._trySubscribe (/home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
      at /home/runner/work/marcolongo.cloud/marcolongo.cloud/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
```

Related issue: #814

**Comment by dianjuar** [comment]
There is a workaround for this issue. You might benefit from it.

https://github.com/jscutlery/semver/issues/814#issuecomment-2159702735

**Comment by marcolongol** [comment]
@dianjuar Awesome, thanks!
