### ISSUE TITLE
Issue with deployment @jscutlery/semver

### ISSUE THREAD

**Issue by minaj2002** [jscutlery/semver#858]
Please give some input on resolving this issue
Error
    at /builds/juliusbaer/ods/odsetl/node_modules/@jscutlery/semver/src/executors/common/exec.js:10:34
    at exithandler (node:child_process:430:5)
    at ChildProcess.errorhandler (node:child_process:442:5)
    at ChildProcess.emit (node:events:[517](https://gitlab.sehlat.io/juliusbaer/ods/odsetl/-/jobs/3728575#L517):28)
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
[odsetl] ❌ Error: Something went wrong with post-target "odsetl:push-gitlab-release".
    at /builds/juliusbaer/ods/odsetl/node_modules/@jscutlery/semver/src/executors/version/utils/post-target.js:25:31
    at Generator.next (<anonymous>)
    at fulfilled (/builds/juliusbaer/ods/odsetl/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[odsetl] ❌ Error: Something went wrong with post-target "odsetl:release-gitlab".
    at /builds/juliusbaer/ods/odsetl/node_modules/@jscutlery/semver/src/executors/version/utils/post-target.js:25:31
    at Generator.next (<anonymous>)
    at fulfilled (/builds/juliusbaer/ods/odsetl/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by edbzn** [comment]
The error says that you have an issue with post-targets "odsetl:push-gitlab-release" and "odsetl:release-gitlab", however I can't help without a reproduction.

**Comment by minaj2002** [comment]
Any issue with my nx file ?
"release-gitlab": {
      "executor": "@jscutlery/semver:version",
      "options": {
        "allowEmptyRelease": true,
        "skipCommit": true,
        "skipTag": true,
        "syncVersions": true,
        "skipPackageJsonUpdate": true,
        "postTargets": ["{projectName}:push-gitlab-release"]
      },
 "push-gitlab-release": {
      "executor": "@jscutlery/semver:gitlab",
      "options": {
        "tag": "${tag}",
        "description": "${notes}"
      }
    },

**Comment by minaj2002** [comment]
I am using the docker image timbru31/java-node:8-hydrogen

**Comment by boy51** [comment]
Did you manage to fix this, I guess this is gitlab release failing
